# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/ravim/OneDrive/Desktop/VivadoProjects/MB_Sensor/MB_Sensor.srcs/sources_1/bd/MB_Sensor/ip/MB_Sensor_ilmb_v10_2/MB_Sensor_ilmb_v10_2.xci
# IP: The module: 'MB_Sensor_ilmb_v10_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ravim/OneDrive/Desktop/VivadoProjects/MB_Sensor/MB_Sensor.srcs/sources_1/bd/MB_Sensor/ip/MB_Sensor_ilmb_v10_2/MB_Sensor_ilmb_v10_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'MB_Sensor_ilmb_v10_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/ravim/OneDrive/Desktop/VivadoProjects/MB_Sensor/MB_Sensor.srcs/sources_1/bd/MB_Sensor/ip/MB_Sensor_ilmb_v10_2/MB_Sensor_ilmb_v10_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MB_Sensor_ilmb_v10_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/ravim/OneDrive/Desktop/VivadoProjects/MB_Sensor/MB_Sensor.srcs/sources_1/bd/MB_Sensor/ip/MB_Sensor_ilmb_v10_2/MB_Sensor_ilmb_v10_2.xci
# IP: The module: 'MB_Sensor_ilmb_v10_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ravim/OneDrive/Desktop/VivadoProjects/MB_Sensor/MB_Sensor.srcs/sources_1/bd/MB_Sensor/ip/MB_Sensor_ilmb_v10_2/MB_Sensor_ilmb_v10_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'MB_Sensor_ilmb_v10_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/ravim/OneDrive/Desktop/VivadoProjects/MB_Sensor/MB_Sensor.srcs/sources_1/bd/MB_Sensor/ip/MB_Sensor_ilmb_v10_2/MB_Sensor_ilmb_v10_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MB_Sensor_ilmb_v10_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
