# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/MB_Sys.xdc

# Block Designs: bd/MB_Sensor/MB_Sensor.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_Sensor || ORIG_REF_NAME==MB_Sensor} -quiet] -quiet

# IP: bd/MB_Sensor/ip/MB_Sensor_clk_wiz_0_1/MB_Sensor_clk_wiz_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_Sensor_clk_wiz_0_1 || ORIG_REF_NAME==MB_Sensor_clk_wiz_0_1} -quiet] -quiet

# IP: bd/MB_Sensor/ip/MB_Sensor_microblaze_0_2/MB_Sensor_microblaze_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_Sensor_microblaze_0_2 || ORIG_REF_NAME==MB_Sensor_microblaze_0_2} -quiet] -quiet

# IP: bd/MB_Sensor/ip/MB_Sensor_dlmb_v10_2/MB_Sensor_dlmb_v10_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_Sensor_dlmb_v10_2 || ORIG_REF_NAME==MB_Sensor_dlmb_v10_2} -quiet] -quiet

# IP: bd/MB_Sensor/ip/MB_Sensor_ilmb_v10_2/MB_Sensor_ilmb_v10_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_Sensor_ilmb_v10_2 || ORIG_REF_NAME==MB_Sensor_ilmb_v10_2} -quiet] -quiet

# IP: bd/MB_Sensor/ip/MB_Sensor_dlmb_bram_if_cntlr_2/MB_Sensor_dlmb_bram_if_cntlr_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_Sensor_dlmb_bram_if_cntlr_2 || ORIG_REF_NAME==MB_Sensor_dlmb_bram_if_cntlr_2} -quiet] -quiet

# IP: bd/MB_Sensor/ip/MB_Sensor_ilmb_bram_if_cntlr_2/MB_Sensor_ilmb_bram_if_cntlr_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_Sensor_ilmb_bram_if_cntlr_2 || ORIG_REF_NAME==MB_Sensor_ilmb_bram_if_cntlr_2} -quiet] -quiet

# IP: bd/MB_Sensor/ip/MB_Sensor_lmb_bram_2/MB_Sensor_lmb_bram_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_Sensor_lmb_bram_2 || ORIG_REF_NAME==MB_Sensor_lmb_bram_2} -quiet] -quiet

# IP: bd/MB_Sensor/ip/MB_Sensor_xbar_2/MB_Sensor_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_Sensor_xbar_2 || ORIG_REF_NAME==MB_Sensor_xbar_2} -quiet] -quiet

# IP: bd/MB_Sensor/ip/MB_Sensor_microblaze_0_axi_periph_2/MB_Sensor_microblaze_0_axi_periph_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_Sensor_microblaze_0_axi_periph_2 || ORIG_REF_NAME==MB_Sensor_microblaze_0_axi_periph_2} -quiet] -quiet

# IP: bd/MB_Sensor/ip/MB_Sensor_microblaze_0_axi_intc_2/MB_Sensor_microblaze_0_axi_intc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_Sensor_microblaze_0_axi_intc_2 || ORIG_REF_NAME==MB_Sensor_microblaze_0_axi_intc_2} -quiet] -quiet

# IP: bd/MB_Sensor/ip/MB_Sensor_microblaze_0_xlconcat_2/MB_Sensor_microblaze_0_xlconcat_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_Sensor_microblaze_0_xlconcat_2 || ORIG_REF_NAME==MB_Sensor_microblaze_0_xlconcat_2} -quiet] -quiet

# IP: bd/MB_Sensor/ip/MB_Sensor_mdm_1_2/MB_Sensor_mdm_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_Sensor_mdm_1_2 || ORIG_REF_NAME==MB_Sensor_mdm_1_2} -quiet] -quiet

# IP: bd/MB_Sensor/ip/MB_Sensor_rst_clk_wiz_0_100M_0/MB_Sensor_rst_clk_wiz_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_Sensor_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==MB_Sensor_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/MB_Sensor/ip/MB_Sensor_axi_iic_0_2/MB_Sensor_axi_iic_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_Sensor_axi_iic_0_2 || ORIG_REF_NAME==MB_Sensor_axi_iic_0_2} -quiet] -quiet

# IP: bd/MB_Sensor/ip/MB_Sensor_auto_pc_18/MB_Sensor_auto_pc_18.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_Sensor_auto_pc_18 || ORIG_REF_NAME==MB_Sensor_auto_pc_18} -quiet] -quiet

# IP: bd/MB_Sensor/ip/MB_Sensor_auto_pc_14/MB_Sensor_auto_pc_14.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_Sensor_auto_pc_14 || ORIG_REF_NAME==MB_Sensor_auto_pc_14} -quiet] -quiet

# IP: bd/MB_Sensor/ip/MB_Sensor_auto_pc_15/MB_Sensor_auto_pc_15.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_Sensor_auto_pc_15 || ORIG_REF_NAME==MB_Sensor_auto_pc_15} -quiet] -quiet

# IP: bd/MB_Sensor/ip/MB_Sensor_auto_pc_16/MB_Sensor_auto_pc_16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_Sensor_auto_pc_16 || ORIG_REF_NAME==MB_Sensor_auto_pc_16} -quiet] -quiet

# IP: bd/MB_Sensor/ip/MB_Sensor_auto_pc_17/MB_Sensor_auto_pc_17.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_Sensor_auto_pc_17 || ORIG_REF_NAME==MB_Sensor_auto_pc_17} -quiet] -quiet

# IP: bd/MB_Sensor/ip/MB_Sensor_processing_system7_0_2/MB_Sensor_processing_system7_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_Sensor_processing_system7_0_2 || ORIG_REF_NAME==MB_Sensor_processing_system7_0_2} -quiet] -quiet

# IP: bd/MB_Sensor/ip/MB_Sensor_axi_uartlite_0_2/MB_Sensor_axi_uartlite_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_Sensor_axi_uartlite_0_2 || ORIG_REF_NAME==MB_Sensor_axi_uartlite_0_2} -quiet] -quiet

# XDC: bd/MB_Sensor/MB_Sensor_ooc.xdc
