# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/ravim/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12220-MSI/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/ravim/OneDrive/Desktop/VivadoProjects/MB_Sensor/MB_Sensor.cache/wt [current_project]
set_property parent.project_path C:/Users/ravim/OneDrive/Desktop/VivadoProjects/MB_Sensor/MB_Sensor.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:cora-z7-10:part0:1.0 [current_project]
set_property ip_repo_paths c:/Arm/M3/vivado/Arm_ipi_repository [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/ravim/OneDrive/Desktop/VivadoProjects/MB_Sensor/MB_Sensor.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/Users/ravim/OneDrive/Desktop/VivadoProjects/MB_Sensor/MB_Sensor.srcs/sources_1/bd/MB_Sensor/hdl/MB_Sensor_wrapper.vhd
add_files C:/Users/ravim/OneDrive/Desktop/VivadoProjects/MB_Sensor/MB_Sensor.srcs/sources_1/bd/MB_Sensor/MB_Sensor.bd
set_property used_in_implementation false [get_files -all c:/Users/ravim/OneDrive/Desktop/VivadoProjects/MB_Sensor/MB_Sensor.srcs/sources_1/bd/MB_Sensor/ip/MB_Sensor_clk_wiz_0_1/MB_Sensor_clk_wiz_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ravim/OneDrive/Desktop/VivadoProjects/MB_Sensor/MB_Sensor.srcs/sources_1/bd/MB_Sensor/ip/MB_Sensor_clk_wiz_0_1/MB_Sensor_clk_wiz_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ravim/OneDrive/Desktop/VivadoProjects/MB_Sensor/MB_Sensor.srcs/sources_1/bd/MB_Sensor/ip/MB_Sensor_clk_wiz_0_1/MB_Sensor_clk_wiz_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ravim/OneDrive/Desktop/VivadoProjects/MB_Sensor/MB_Sensor.srcs/sources_1/bd/MB_Sensor/ip/MB_Sensor_microblaze_0_2/MB_Sensor_microblaze_0_2.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ravim/OneDrive/Desktop/VivadoProjects/MB_Sensor/MB_Sensor.srcs/sources_1/bd/MB_Sensor/ip/MB_Sensor_microblaze_0_2/MB_Sensor_microblaze_0_2_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ravim/OneDrive/Desktop/VivadoProjects/MB_Sensor/MB_Sensor.srcs/sources_1/bd/MB_Sensor/ip/MB_Sensor_microblaze_0_2/MB_Sensor_microblaze_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ravim/OneDrive/Desktop/VivadoProjects/MB_Sensor/MB_Sensor.srcs/sources_1/bd/MB_Sensor/ip/MB_Sensor_dlmb_v10_2/MB_Sensor_dlmb_v10_2.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ravim/OneDrive/Desktop/VivadoProjects/MB_Sensor/MB_Sensor.srcs/sources_1/bd/MB_Sensor/ip/MB_Sensor_dlmb_v10_2/MB_Sensor_dlmb_v10_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ravim/OneDrive/Desktop/VivadoProjects/MB_Sensor/MB_Sensor.srcs/sources_1/bd/MB_Sensor/ip/MB_Sensor_ilmb_v10_2/MB_Sensor_ilmb_v10_2.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ravim/OneDrive/Desktop/VivadoProjects/MB_Sensor/MB_Sensor.srcs/sources_1/bd/MB_Sensor/ip/MB_Sensor_ilmb_v10_2/MB_Sensor_ilmb_v10_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ravim/OneDrive/Desktop/VivadoProjects/MB_Sensor/MB_Sensor.srcs/sources_1/bd/MB_Sensor/ip/MB_Sensor_dlmb_bram_if_cntlr_2/MB_Sensor_dlmb_bram_if_cntlr_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ravim/OneDrive/Desktop/VivadoProjects/MB_Sensor/MB_Sensor.srcs/sources_1/bd/MB_Sensor/ip/MB_Sensor_ilmb_bram_if_cntlr_2/MB_Sensor_ilmb_bram_if_cntlr_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ravim/OneDrive/Desktop/VivadoProjects/MB_Sensor/MB_Sensor.srcs/sources_1/bd/MB_Sensor/ip/MB_Sensor_lmb_bram_2/MB_Sensor_lmb_bram_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ravim/OneDrive/Desktop/VivadoProjects/MB_Sensor/MB_Sensor.srcs/sources_1/bd/MB_Sensor/ip/MB_Sensor_xbar_2/MB_Sensor_xbar_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ravim/OneDrive/Desktop/VivadoProjects/MB_Sensor/MB_Sensor.srcs/sources_1/bd/MB_Sensor/ip/MB_Sensor_microblaze_0_axi_intc_2/MB_Sensor_microblaze_0_axi_intc_2.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ravim/OneDrive/Desktop/VivadoProjects/MB_Sensor/MB_Sensor.srcs/sources_1/bd/MB_Sensor/ip/MB_Sensor_microblaze_0_axi_intc_2/MB_Sensor_microblaze_0_axi_intc_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ravim/OneDrive/Desktop/VivadoProjects/MB_Sensor/MB_Sensor.srcs/sources_1/bd/MB_Sensor/ip/MB_Sensor_microblaze_0_axi_intc_2/MB_Sensor_microblaze_0_axi_intc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ravim/OneDrive/Desktop/VivadoProjects/MB_Sensor/MB_Sensor.srcs/sources_1/bd/MB_Sensor/ip/MB_Sensor_mdm_1_2/MB_Sensor_mdm_1_2.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ravim/OneDrive/Desktop/VivadoProjects/MB_Sensor/MB_Sensor.srcs/sources_1/bd/MB_Sensor/ip/MB_Sensor_mdm_1_2/MB_Sensor_mdm_1_2_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ravim/OneDrive/Desktop/VivadoProjects/MB_Sensor/MB_Sensor.srcs/sources_1/bd/MB_Sensor/ip/MB_Sensor_rst_clk_wiz_0_100M_0/MB_Sensor_rst_clk_wiz_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ravim/OneDrive/Desktop/VivadoProjects/MB_Sensor/MB_Sensor.srcs/sources_1/bd/MB_Sensor/ip/MB_Sensor_rst_clk_wiz_0_100M_0/MB_Sensor_rst_clk_wiz_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ravim/OneDrive/Desktop/VivadoProjects/MB_Sensor/MB_Sensor.srcs/sources_1/bd/MB_Sensor/ip/MB_Sensor_rst_clk_wiz_0_100M_0/MB_Sensor_rst_clk_wiz_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ravim/OneDrive/Desktop/VivadoProjects/MB_Sensor/MB_Sensor.srcs/sources_1/bd/MB_Sensor/ip/MB_Sensor_axi_iic_0_2/MB_Sensor_axi_iic_0_2_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ravim/OneDrive/Desktop/VivadoProjects/MB_Sensor/MB_Sensor.srcs/sources_1/bd/MB_Sensor/ip/MB_Sensor_axi_iic_0_2/MB_Sensor_axi_iic_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ravim/OneDrive/Desktop/VivadoProjects/MB_Sensor/MB_Sensor.srcs/sources_1/bd/MB_Sensor/ip/MB_Sensor_auto_pc_18/MB_Sensor_auto_pc_18_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ravim/OneDrive/Desktop/VivadoProjects/MB_Sensor/MB_Sensor.srcs/sources_1/bd/MB_Sensor/ip/MB_Sensor_auto_pc_14/MB_Sensor_auto_pc_14_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ravim/OneDrive/Desktop/VivadoProjects/MB_Sensor/MB_Sensor.srcs/sources_1/bd/MB_Sensor/ip/MB_Sensor_auto_pc_15/MB_Sensor_auto_pc_15_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ravim/OneDrive/Desktop/VivadoProjects/MB_Sensor/MB_Sensor.srcs/sources_1/bd/MB_Sensor/ip/MB_Sensor_auto_pc_16/MB_Sensor_auto_pc_16_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ravim/OneDrive/Desktop/VivadoProjects/MB_Sensor/MB_Sensor.srcs/sources_1/bd/MB_Sensor/ip/MB_Sensor_auto_pc_17/MB_Sensor_auto_pc_17_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ravim/OneDrive/Desktop/VivadoProjects/MB_Sensor/MB_Sensor.srcs/sources_1/bd/MB_Sensor/ip/MB_Sensor_processing_system7_0_2/MB_Sensor_processing_system7_0_2.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ravim/OneDrive/Desktop/VivadoProjects/MB_Sensor/MB_Sensor.srcs/sources_1/bd/MB_Sensor/ip/MB_Sensor_axi_uartlite_0_2/MB_Sensor_axi_uartlite_0_2_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ravim/OneDrive/Desktop/VivadoProjects/MB_Sensor/MB_Sensor.srcs/sources_1/bd/MB_Sensor/ip/MB_Sensor_axi_uartlite_0_2/MB_Sensor_axi_uartlite_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ravim/OneDrive/Desktop/VivadoProjects/MB_Sensor/MB_Sensor.srcs/sources_1/bd/MB_Sensor/ip/MB_Sensor_axi_uartlite_0_2/MB_Sensor_axi_uartlite_0_2.xdc]
set_property used_in_implementation false [get_files -all C:/Users/ravim/OneDrive/Desktop/VivadoProjects/MB_Sensor/MB_Sensor.srcs/sources_1/bd/MB_Sensor/MB_Sensor_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ravim/OneDrive/Desktop/VivadoProjects/MB_Sensor/MB_Sensor.srcs/sources_1/bd/MB_Sensor/ip/MB_Sensor_microblaze_0_2/data/mb_bootloop_le.elf]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/ravim/OneDrive/Desktop/VivadoProjects/MB_Sensor/MB_Sensor.srcs/constrs_1/new/MB_Sys.xdc
set_property used_in_implementation false [get_files C:/Users/ravim/OneDrive/Desktop/VivadoProjects/MB_Sensor/MB_Sensor.srcs/constrs_1/new/MB_Sys.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top MB_Sensor_wrapper -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef MB_Sensor_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file MB_Sensor_wrapper_utilization_synth.rpt -pb MB_Sensor_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
